### ISSUE TITLE
setA11yContent() entwertet HTML-Befehle

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/vidstack#30]
Wenn ich mit `$video->setA11yContent('Mein Text<br>in der zweiten Zeile.');` einen Text hinterlege, dann werden die HTML-Befehle entwertet.

Ergebnis: `Mein Text&lt;br&gtin der zweiten Zeile.`

Besser wäre eine Option, um die HTML-Zeichen korrekt ausgeben zu können.

**Comment by skerbis** [comment]
Bitte testen
